openapi: 3.2.0
info:
  title: Outbrain Amplify Users API
  version: '0.1'
  description: This API describes the interfaces for interacting with the Outbrain Amplify product.
  contact:
    name: Outbrain Developer Center
    url: https://developer.outbrain.com
servers:
- url: https://api.outbrain.com/amplify/v0.1
  description: Production Server
security:
- OBTokenAuth: []
tags:
- name: Users
  description: 'User represents a single person''s access to Outbrain services and to the site my.outbrain.com.

    A User is permitted to one or more Marketer accounts, each marketer with a role that specifies the user permissions.'
paths:
  /marketers/{marketerId}/users:
    get:
      operationId: getMarketersMarketerIdUsers
      summary: Getting all users permitted to a marketer
      description: 'The response contains an array of a user object that has the following attributes:


        Property

        Type

        Semantic

        Example


        name

        String

        The User''s name

        "full name"


        email

        String

        The User''s email

        "a@b.ocm"


        creationTime

        Time

        The time when the user was assigned to the marketer

        "2013-01-14 07:19:16"


        status

        String

        The User''s status - ACTIVE, PENDING, DISABLED

        "ACTIVE"


        invitationId

        String

        The invitation ID of the user in case the user has a pending invitation


        fullName

        String

        The user''s full name


        role

        User Role

        The user''s role

        "ACCOUNT_MANAGER"'
      tags:
      - Users
      parameters:
      - name: marketerId
        in: path
        required: true
        schema:
          type: string
        description: the Marketer's id
        example: 00f4b02153ee75f3c9dc4fc128ab041962
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
              example:
                users:
                - name: somename1
                  email: user1@domain.com
                  creationTime: '2022-09-20 20:12:23'
                  status: ACTIVE
                  fullName: some name1
                  role: ACCOUNT_MANAGER
                - name: somename2
                  email: user2@domain.com
                  creationTime: '2022-09-20 20:12:23'
                  status: PENDING
                  invitationId: 00f4b02153ee75f3c9dc4fc128ab041962
                  role: ACCOUNT_MANAGER
          headers:
            AMPLIFY-REQUEST-ID:
              description: Request correlation / rate-limit signal
              schema:
                type: string
        '400':
          description: Bad Request - the request could not be understood or was missing required parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - authentication failed or the user lacks permission for the requested operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found - resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too Many Requests - request exceeded rate limits; see the rate-limit-msec-left header
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      operationId: updateMarketersMarketerIdUsers
      summary: Update marketer's users
      description: Update marketer's users allows disabling/enabling a user and updating their role
      tags:
      - Users
      parameters:
      - name: marketerId
        in: path
        required: true
        schema:
          type: string
        description: the Marketer's id
        example: 00f4b02153ee75f3c9dc4fc128ab041962
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
            - userEmail: a@mydomain.com
              enabled: true
              role: VIEWER
            - userEmail: b@mydomain.com
              enabled: true
              role: CAMPAIGN_MANAGER
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
              example:
                users:
                - name: somename1
                  email: a@domain.com
                  creationTime: '2022-09-20 20:12:23'
                  status: DISABLED
                  fullName: some name1
                  role: ACCOUNT_MANAGER
                - name: somename2
                  email: b@domain.com
                  creationTime: '2022-09-20 20:12:23'
                  status: ENABLED
                  invitationId: 00f4b02153ee75f3c9dc4fc128ab041962
                  role: VIEWER
          headers:
            AMPLIFY-REQUEST-ID:
              description: Request correlation / rate-limit signal
              schema:
                type: string
        '400':
          description: Bad Request - the request could not be understood or was missing required parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - authentication failed or the user lacks permission for the requested operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found - resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too Many Requests - request exceeded rate limits; see the rate-limit-msec-left header
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      operationId: deleteMarketersMarketerIdUsers
      summary: Remove a user from a marketer
      description: This endpoint allows revoking a permission for a user to access a marketer.
      tags:
      - Users
      parameters:
      - name: marketerId
        in: path
        required: true
        schema:
          type: string
        description: the Marketer's id
        example: 00f4b02153ee75f3c9dc4fc128ab041962
      - name: email
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          headers:
            AMPLIFY-REQUEST-ID:
              description: Request correlation / rate-limit signal
              schema:
                type: string
        '400':
          description: Bad Request - the request could not be understood or was missing required parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - authentication failed or the user lacks permission for the requested operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found - resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too Many Requests - request exceeded rate limits; see the rate-limit-msec-left header
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /invitations/multiple:
    post:
      operationId: createInvitationsMultiple
      summary: Providing access for new users to a marketer
      tags:
      - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
            - marketerId: 007514a95316bh6fe7ejc0cad101c23343
              invitedEmail: a@mydomain.com
              role: ADMIN
            - marketerId: 007514a95316bh6fe7ejc0cad101c23343
              invitedEmail: b@mydomain.com
              role: VIEWER
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
              example: "[\n    {\n        \"id\": \"007514a95316bh6fe7ejc0cad101c23343\",\n        \"invitingUserEmail\": \"admin@mydomain.com\",\n        \"invitedEmail\": \"a@mydomain.com\",\n        \"marketerId\": \"007514a95316bh6fe7ejc0cad101c23343\",\n        \"status\": \"Pending\",\n        \"creationDate\": \"2022-06-01\",\n        \"marketerName\": \"Some marketer\",\n        \"role\": \"ADMIN\"\n    },\n       \"id\": \"007514a95316bh6fe7ejc0cad101c23343\",\n        \"invitingUserEmail\": \"admin@mydomain.com\",\n        \"invitedEmail\": \"b@mydomain.com\",\n        \"marketerId\": \"007514a95316bh6fe7ejc0cad101c23343\",\n        \"status\": \"Pending\",\n        \"creationDate\": \"2022-06-01\",\n        \"marketerName\": \"Some marketer\",\n        \"role\": \"VIEWER\"\n    }\n]"
          headers:
            AMPLIFY-REQUEST-ID:
              description: Request correlation / rate-limit signal
              schema:
                type: string
        '400':
          description: Bad Request - the request could not be understood or was missing required parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - authentication failed or the user lacks permission for the requested operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found - resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too Many Requests - request exceeded rate limits; see the rate-limit-msec-left header
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /invitations:
    put:
      operationId: updateInvitations
      summary: Delete pending invitations
      description: Delete pending invitations should be done by updating the status of the invitations to REVOKED
      tags:
      - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              invitations:
              - id: 007514a95316bh6fe7ejc0cad101c23349
                status: REVOKED
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
              example: "{\n    \"updatedInvitations\":\n     [\n        {\n            \"operationStatus\":\n                {\n                \"status\": \"Success\"\n                }\n            \"invitation\":\n                {\n                \"id\": \"007514a95316bh6fe7ejc0cad101c23349\",\n                \"invitingUserEmail\": \"admin@mydomain.com\",\n                \"invitedEmail\": \"a@mydomain.com\",\n                \"marketerId\": \"007514a95316bh6fe7ejc0cad101c23343\",\n                \"status\": \"Revoked\",\n                \"creationDate\": \"2022-06-01\",\n                \"marketerName\": \"Some marketer\",\n                \"role\": \"ADMIN\"\n                },\n        \"id\": \"007514a95316bh6fe7ejc0cad101c23349\"\n        }\n    ]\n}"
          headers:
            AMPLIFY-REQUEST-ID:
              description: Request correlation / rate-limit signal
              schema:
                type: string
        '400':
          description: Bad Request - the request could not be understood or was missing required parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - authentication failed or the user lacks permission for the requested operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found - resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too Many Requests - request exceeded rate limits; see the rate-limit-msec-left header
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      description: Error envelope returned on 400/401/403/404/429 responses.
      properties:
        moreInfo:
          type: string
          description: Short machine-readable hint identifying the failing operation.
        errorMessage:
          type: string
          description: Human-readable error message.
      examples:
      - moreInfo: get-budget
        errorMessage: access denied
  securitySchemes:
    OBTokenAuth:
      type: apiKey
      in: header
      name: OB-TOKEN-V1
      description: Token obtained from GET /login (HTTP Basic) or from https://my.outbrain.com/create-token. Valid for 30 days.
    BasicAuth:
      type: http
      scheme: basic
      description: HTTP Basic credentials used only on GET /login to obtain an OB-TOKEN-V1 token.
